# -*- coding: utf-8 -*-
"""OOP Problems.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xTkpTEL2Be5eCqAAy1-2h3ozttk_UKhC

# **OOP Problems**

### **Problem 1**
**Implement a complex number class. Overload the addition and subtraction operators to add and subtract two complex numbers.**
"""

class Complex:
    def __init__(self, real, imag):
        self.real = real
        self.imag = imag

    # overload +
    def __add__(self, other):
        real_part = self.real + other.real
        imag_part = self.imag + other.imag
        return Complex(real_part, imag_part)

    # overload -
    def __sub__(self, other):
        real_part = self.real - other.real
        imag_part = self.imag - other.imag
        return Complex(real_part, imag_part)

    def __str__(self):
        return f"{self.real} + {self.imag}i"

c1 = Complex(2, 3)
c2 = Complex(1, 4)

c3 = c1 + c2
c4 = c1 - c2

print(c3)
print(c4)

"""### **Problem 2**
**Create a class Person with name, age and gender as its attributes. Overload the > operator to compare two persons based on their age, such that p1 > p2 returns True if the age of p1 is greater than p2 and False otherwise.**
"""

class Person:
    def __init__(self, name, age, gender):
        self.name = name
        self.age = age
        self.gender = gender

    # overload >
    def __gt__(self, other):
        return self.age > other.age

    def __str__(self):
        return f"{self.name}, {self.age}, {self.gender}"

p1 = Person("Alice", 25, "F")
p2 = Person("Bob", 20, "M")

print(p1 > p2)
print(p2 > p1)

"""### **Problem 3**
**Create a class Vector that represents a vector in space, with x, y, and z as its attributes. Overload the * operator to return the dot product of two vectors, such that vector1 * vector2 returns the dot product of the two input vectors.**
"""

class Vector:
    def __init__(self, x, y, z):
        self.x = x
        self.y = y
        self.z = z

    # overload *
    def __mul__(self, other):
        return (self.x * other.x +
                self.y * other.y +
                self.z * other.z)

    def __str__(self):
        return f"({self.x}, {self.y}, {self.z})"

v1 = Vector(1, 2, 3)
v2 = Vector(4, 5, 6)

result = v1 * v2

print(result)

"""### **Problem 4**
**Overload all comparison operators (<, >, ==, !=, >=, <=) for a Circle class based on radius.**
"""

class Circle:
    def __init__(self, radius):
        self.radius = radius

    def __lt__(self, other):
        return self.radius < other.radius

    def __gt__(self, other):
        return self.radius > other.radius

    def __eq__(self, other):
        return self.radius == other.radius

    def __ne__(self, other):
        return self.radius != other.radius

    def __le__(self, other):
        return self.radius <= other.radius

    def __ge__(self, other):
        return self.radius >= other.radius

    def __str__(self):
        return f"Circle(radius={self.radius})"

c1 = Circle(5)
c2 = Circle(3)

print(c1 > c2)
print(c1 < c2)
print(c1 == c2)
print(c1 != c2)
print(c1 >= c2)
print(c1 <= c2)

"""### **Problem 5**
**Implement a 2D point class. Overload the comparison operators to compare two points based on their Euclidean distance from the origin. Euclidean distance = sqrt(x² + y²)**
"""

class Point:
    def __init__(self, x, y):
        self.x = x
        self.y = y

    def distance_sq(self):
        return self.x**2 + self.y**2

    def __lt__(self, other):
        return self.distance_sq() < other.distance_sq()

    def __gt__(self, other):
        return self.distance_sq() > other.distance_sq()

    def __eq__(self, other):
        return self.distance_sq() == other.distance_sq()

    def __str__(self):
        return f"({self.x}, {self.y})"

p1 = Point(3, 4)
p2 = Point(1, 1)

print(p1 > p2)
print(p1 < p2)

"""### **Problem 6**
**Overload the multiplication operator for two matrices.**
"""

class Matrix:
    def __init__(self, data):
        self.data = data  # list of lists

    def __mul__(self, other):
        result = []

        # rows of A
        for i in range(len(self.data)):
            row = []
            # columns of B
            for j in range(len(other.data[0])):
                sum_val = 0
                # multiplication
                for k in range(len(self.data[0])):
                    sum_val += self.data[i][k] * other.data[k][j]
                row.append(sum_val)
            result.append(row)

        return Matrix(result)

    def __str__(self):
        return "\n".join(str(row) for row in self.data)

A = Matrix([[1, 2],
            [3, 4]])

B = Matrix([[5, 6],
            [7, 8]])

C = A * B

print(C)

"""## **Inheritance**

### **Problem 1**
**Create a class Vehicle that has a method drive that returns the string "Driving a vehicle". Create two subclasses, Car and Bicycle, that override this method to return "Driving a car" and "Riding a bicycle", respectively.**
"""

class Vehicle:
    def drive(self):
        return "Driving a vehicle"

class Car(Vehicle):
    def drive(self):
        return "Driving a car"

class Bicycle(Vehicle):
    def drive(self):
        return "Riding a bicycle"

v = Vehicle()
c = Car()
b = Bicycle()

print(v.drive())
print(c.drive())
print(b.drive())

"""### **Problem 2**
**Create a class Person with attributes: name, age, address and method: introduce.**

**Create a subclass Student of the class Person that has an attribute: field_of_study and a personalized method: introduce.**

**Create another subclass Employee of the class Person that has an attribute: company and a personalized method: introduce.**
"""

class Person:
    def __init__(self, name, age, address):
        self.name = name
        self.age = age
        self.address = address

    def introduce(self):
        return f"My name is {self.name}, I am {self.age} years old."


class Student(Person):
    def __init__(self, name, age, address, field_of_study):
        super().__init__(name, age, address)
        self.field_of_study = field_of_study

    def introduce(self):
        return f"My name is {self.name}, I study {self.field_of_study}."


class Employee(Person):
    def __init__(self, name, age, address, company):
        super().__init__(name, age, address)
        self.company = company

    def introduce(self):
        return f"My name is {self.name}, I work at {self.company}."

p = Person("Anna", 25, "Paris")
s = Student("Bob", 20, "London", "Computer Science")
e = Employee("Cris", 30, "NYC", "Google")

print(p.introduce())
print(s.introduce())
print(e.introduce())

"""### **Problem 3**
**Define two classes, BankAccount and SavingsAccount:**

**- BankAccount has attributes account_number and balance, and methods deposit and withdraw**
**- SavingsAccount inherits from BankAccount and adds interest_rate attribute and add_interest method**
**- Add a check_balance method to SavingsAccount**
**- Add a transfer method to BankAccount that transfers money to a destination account (return False if insufficient balance, True otherwise)**
"""

class BankAccount:
    def __init__(self, account_number, balance):
        self.account_number = account_number
        self.balance = balance

    def deposit(self, amount):
        self.balance += amount

    def withdraw(self, amount):
        if amount > self.balance:
            return False
        self.balance -= amount
        return True

    def transfer(self, amount, destination_account):
        if self.balance < amount:
            return False
        self.balance -= amount
        destination_account.balance += amount
        return True


class SavingsAccount(BankAccount):
    def __init__(self, account_number, balance, interest_rate):
        super().__init__(account_number, balance)
        self.interest_rate = interest_rate

    def add_interest(self):
        interest = self.balance * self.interest_rate
        self.balance += interest

    def check_balance(self):
        return self.balance

acc1 = SavingsAccount("A123", 1000, 0.05)
acc2 = SavingsAccount("B456", 500, 0.03)

# deposit
acc1.deposit(200)

# withdraw
acc1.withdraw(100)

# transfer
success = acc1.transfer(300, acc2)
print(success)

# add interest
acc1.add_interest()

# check balance
print(acc1.check_balance())
print(acc2.check_balance())